#!/data/data/com.termux/files/usr/bin/bash

# Look for new ROMs since the last run.

##### Config #####
# Don't edit the configuration in this file as it would be overwritten on updates.
# Create the file .config/pegasus_android_helpers.conf and override the variables.

module=screenscraper
exclude=("android")

##################
if [[ -f ~/.config/pegasus_android_helpers.conf ]]; then
    source ~/.config/pegasus_android_helpers.conf
fi

#---------------
lastrun=~/.skyscraper/skyscraper.lastrun 

if [ ! -f ${lastrun} ]; then
    echo "First run: this could take a long time..."
    # create a lastrun file far in the past to scan everything
    touch -d "1/1/1970" ${lastrun}
fi
#---------------

inputline=$(grep -m 1 inputFolder ~/.skyscraper/config.ini)
rompath=${inputline##*=}
rompath="${rompath%\"}"
rompath="${rompath#\"}"

echo Looking for new ROMs in $rompath

systems=$(find ${rompath} -mindepth 2 -maxdepth 2 -type f -cnewer ${lastrun} -exec sh -c 'basename $(dirname "$0")' {} \; | sort | uniq)

if [[ "$systems" == "" ]];then
    echo "No new game found."
fi

for system in $systems
do
    for i in "${exclude[@]}"
    do
        if [ "$i" == "$system" ] ; then
            echo "Skipping $system"
            skip=true
        fi
    done
    if ! $skip ; then
        echo Processing $system ...

        if [ "$system" = "mame" ]; then
            system="mame-libretro"
        elif [ "$system" = "fbneo" ]; then
            system="fba"
        fi

        Skyscraper -p ${system} -s ${module} --flags unattendskip
        Skyscraper -p ${system} --flags unattendskip
    fi
    skip=false
done

# Update lastrun
touch ${lastrun}

# If launched from a Termux shortcut, closes automatically
# wait for a key press
read -n 1 -r -s -p "Press any key to continue..." key
echo ""

